apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: analizapc-backend
  labels:
    app: analizapc-backend
    version: "1.0"
spec:
  replicas: 1
  selector:
    app: analizapc-backend
    deploymentconfig: analizapc-backend
  template:
    metadata:
      labels:
        app: analizapc-backend
        deploymentconfig: analizapc-backend
    spec:
      containers:
      - name: analizapc-backend
        image: analizapc-backend:latest
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
        - name: DROPBOX_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: dropbox-secret
              key: token
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: analizapc-backend
  labels:
    app: analizapc-backend
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: analizapc-backend
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: analizapc-backend
  labels:
    app: analizapc-backend
spec:
  to:
    kind: Service
    name: analizapc-backend
  port:
    targetPort: 8000